#!/usr/bin/with-contenv sh
# use with-contenv to access env vars

# When using a url path prefix, eg http://localhost/path/to/ttrss, static
# files can't be found. So we create a symlink so that path/to/ttrss points
# at the base ttrss directory. Ensure the url path prefix doesn't clash with
# any files

# get url path prefix
# TTRSS_SELF_URL_PATH=https://localhost/path/to/ttrss
# URL_PATH_PREFIX=path/to/ttrss
URL_PATH_PREFIX="$(echo ${TTRSS_SELF_URL_PATH} | cut -d '/' -f 4-)"

# if there is no url path prefix, we can exit
if [ -z "${URL_PATH_PREFIX}" ]; then
  exit 0
fi

# create subdirectories in base ttrss directory
# URL_PATH_PREFIX=path/to/ttrss
# SYMLINK_DIRNAME=path/to
SYMLINK_DIRNAME="$(dirname ${URL_PATH_PREFIX})"
mkdir -p "/var/www/localhost/htdocs/${SYMLINK_DIRNAME}"
if [ $? -ne 0 ]; then
  echo "!!! ERROR !!! Could not create directory /var/www/localhost/htdocs/${SYMLINK_DIRNAME}"
  exit 1
fi

# create symlink to base ttrss directory
ln -sf /var/www/localhost/htdocs "/var/www/localhost/htdocs/${URL_PATH_PREFIX}"
if [ $? -ne 0 ]; then
  echo "!!! ERROR !!! Could not create symlink /var/www/localhost/htdocs/${URL_PATH_PREFIX}"
  exit 1
fi
